# Bell States, Measurements, and Expectation Values

In [1]:
import pennylane as qml
from pennylane import numpy as np

In [2]:
dev1 = qml.device("default.qubit", wires=2, shots=10)

## Bell States

### State 1
$|00\rangle = |0\rangle \otimes |0\rangle = \begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} 1\\0\\0\\0 \end{pmatrix} \mapsto CNOT(H|0\rangle \otimes I|0\rangle)$

Now, let's have a look at what $CNOT(H|0\rangle \otimes I|0\rangle)$ is:

$ =\begin{pmatrix}1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{pmatrix} \left(\frac{1}{\sqrt{2}}\begin{pmatrix}1 & 1\\ 1 & -1 \end{pmatrix}\begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 1\\ 0 \end{pmatrix}\right)$ 

$ = \begin{pmatrix}1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{pmatrix}\left( \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} \right)$

$ = \frac{1}{\sqrt{2}}\begin{pmatrix}1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{pmatrix} \begin{pmatrix} 1\\0\\1\\0 \end{pmatrix}$

$ = \frac{1}{\sqrt{2}} \begin{pmatrix} 1\\0\\0\\1 \end{pmatrix}$

$ = \frac{|00\rangle + |11\rangle}{\sqrt{2}} = |\beta_{00}\rangle$

Now let's compute an expectation value using the Pauli-Z operator:

$\langle \beta_{00} | I \otimes Z | \beta_{00} \rangle = \begin{pmatrix}1, &0, &0, &1 \end{pmatrix} \begin{pmatrix} 1&0&0&0\\0&-1&0&0\\0&0&1&0\\0&0&0&-1 \end{pmatrix} \begin{pmatrix} 1\\0\\0\\1 \end{pmatrix} = 0$

The following quantum circuit computes this expectation value, as well as the expectation value $\langle \beta_{00} | Z \otimes I | \beta_{00} \rangle$, and outputs a numpy array $[0. \ 0.]$. 

In [3]:
n = np.array([0, 0])
@qml.qnode(dev1)
def circuit():
    qml.BasisState(n, wires=[0, 1])
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.expval(qml.PauliZ(0)), qml.expval(qml.PauliZ(1))

print(circuit())

[0. 0.]


The next circuit measures the quantum circuit 10 times, which is specified by the number of shots parameter in the definition of the quantum device 'dev1' being used. It outputs the measurements using the observables $Z \otimes I$ and $I \otimes Z$ in an array. We can see that the pair of measurement outcomes in all ten cases match, which is to be expected from the entanglement and the intitial state $|00\rangle$. 

In [4]:
n = np.array([0, 0])
@qml.qnode(dev1)
def circuit():
    qml.BasisState(n, wires=[0, 1])
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[-1. -1. -1.  1. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1. -1. -1.]]


### State 2
In the following circuit, we sample the same circuit, except we prepare the initial state to be $|10\rangle$. 

In [5]:
n = np.array([1, 0])
@qml.qnode(dev1)
def circuit():
    qml.BasisState(n, wires=[0, 1])
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[-1. -1. -1. -1.  1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1. -1. -1. -1. -1.  1.]]


### Exercize 2.1
As an exercise, draw the circuit diagram and write out the linear algebra involved in this computation. 

### Exercise 2.2
Now compose a circuit that measures the expectation values of $\langle \beta_{10}| Z \otimes I | \beta_{10} \rangle$ and $\langle \beta_{10}|I \otimes Z|\beta_{10}\rangle$ for the intitial state $|10\rangle$ which gives the output state $|\beta_{10}\rangle$ that you computed in the previous exercise.

### State 3
In the following circuit, we sample the same circuit, except we prepare the initial state to be $|01\rangle$.

In [6]:
n = np.array([0, 1])
@qml.qnode(dev1)
def circuit():
    qml.BasisState(n, wires=[0, 1])
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[ 1. -1.  1.  1. -1. -1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1. -1.  1.  1.  1.  1.]]


### Exercize 3.1
As an exercise, draw the circuit diagram and write out the linear algebra involved in this computation. 

### Exercise 3.2
Now compose a circuit that measures the expectation values of $\langle \beta_{01}| Z \otimes I | \beta_{01} \rangle$ and $\langle \beta_{01}|I \otimes Z|\beta_{01}\rangle$ for the intitial state $|01\rangle$ which gives the output state $|\beta_{01}\rangle$ that you computed in the previous exercise.

### State 4
In the following circuit, we sample the same circuit, except we prepare the initial state to be $|11\rangle$.

In [7]:
n = np.array([1, 1])
@qml.qnode(dev1)
def circuit():
    qml.BasisState(n, wires=[0, 1])
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[-1.  1. -1. -1.  1. -1.  1. -1.  1.  1.]
 [-1.  1. -1. -1.  1.  1. -1.  1.  1.  1.]]


### Exercize 4.1
As an exercise, draw the circuit diagram and write out the linear algebra involved in this computation. 

### Exercise 4.2
Now compose a circuit that measures the expectation values of $\langle \beta_{11}| Z \otimes I | \beta_{11} \rangle$ and $\langle \beta_{11}|I \otimes Z|\beta_{11}\rangle$ for the intitial state $|11\rangle$ which gives the output state $|\beta_{11}\rangle$ that you computed in the previous exercise.